---
- hosts: javaserver
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes  # Corrected indentation

    - include_tasks: createfileplaybook.yml  # Ensure this is at the correct indentation level

    - name: Install apache2 on node server
      apt:
        name: apache2
        state: present  # Corrected indentation
      notify: restartedservice

    - name: I want to replace apache vertex package
      template:
          src: newtemplatefile.j2
          dest: /var/www/html/index.html
      notify: restartedservice

  handlers:
      - name: restartedservice
        service:
          name: apache2
          state: restarted
