---
- hosts: javaserver
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes  # Corrected indentation

    - include_tasks: createfileplaybook.yml  # Ensure this is at the correct indentation level

    - name: Install apache2 on node server
      apt:
        name: apache2
        state: present  # Corrected indentation
