---
- hosts: javaserver
  become: yes
  tasks:
    - name: Execute Linux command to get fully qualified hostname
      command: hostname -f
      register: myResult

    - name: Display the command result
      debug:
        msg: "{{ myResult }}"

    - name: Install git if the command was successful
      apt:
        name: git
        state: present
      when: myResult.rc == "" 

    - name: Install tree if the command failed
      apt:
        name: tree
        state: present
      when: myResult.rc != ""
