---
  - hosts: javaserver
    become: yes
    vars:
      myvars1: git
      myvars2: tree
      myvars3: apache2
    tasks:
      - name: Display variable1
        debug:
          msg: "{{ myvars3 }}"

      - name: Install package
        apt:
          name: "{{ item }}"
          state: present
        loop:
          - "{{ myvars1 }}"
          - "{{ myvars2 }}"
          - "{{ myvars3 }}"