---
  - hosts: javaserver
    become: yes
    vars:
      myvars1: git
      myvars2: tree
      myvars3: apache2
    tasks:
      - name: Display variable1
        debug:
          msg: "{{ myvars1}}"