---
- hosts: all
  become: yes
  vars:
    myubuntujavapackage: "openjdk-8-jdk"  
    myredhatpackage: "java-1.8.0-openjdk"

  tasks:
    - name: Install openjdk on Debian
      apt:
        name: "{{ myubuntujavapackage }}"
        state: present
      when: ansible_os_family == "Debian"

    - name: Install open jdk 8 on RedHat server
      yum:
        name: "{{ myredhatpackage }}"
        state: present
      when: ansible_os_family == "RedHat"
      
